"""Change quantity_available to Integer

Revision ID: 7a3737442910
Revises: c95e8ecbd791
Create Date: 2025-06-03 10:23:00.356949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3737442910'
down_revision: Union[str, None] = 'c95e8ecbd791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
    'ALTER TABLE merch_items ALTER COLUMN quantity_available TYPE INTEGER USING quantity_available::integer'
    )   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merch_items', 'quantity_available',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
